apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: export-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: rawdatalabs.cloud/v1
    resource: exports
  childResources:
  - apiVersion: batch/v1
    resource: jobs
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://export-controller.metacontroller/sync